version: "3"

services:
  db:
    image: "postgres"
    env_file:
      - ../.envrc
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  db-data:
